/**
 * 模型供应商注册表
 *
 * 数据来源：
 *   1. hermes-backend/hermes_cli/providers.py -> HERMES_OVERLAYS (35 个)
 *   2. hermes-backend/agent/models_dev.py -> models.dev 集成 (109+ 供应商)
 *   3. hermes-backend/hermes_cli/providers.py -> ALIASES (别名映射)
 *
 * 提取时间：2026-05-16
 */

import type { ProviderDef } from '@/shared/agent-types'

export const PROVIDERS: ProviderDef[] = [
  // === 国际大厂 ===
  {
    id: 'openai',
    name: 'OpenAI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['OPENAI_API_KEY'],
    baseUrl: 'https://api.openai.com/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://platform.openai.com/docs',
    source: 'models-dev',
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    transport: 'anthropic_messages',
    apiKeyEnvVars: ['ANTHROPIC_API_KEY', 'ANTHROPIC_TOKEN', 'CLAUDE_CODE_OAUTH_TOKEN'],
    baseUrl: 'https://api.anthropic.com',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['claude', 'claude-code'],
    doc: 'https://docs.anthropic.com',
    source: 'hermes',
  },
  {
    id: 'google',
    name: 'Google (Gemini)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['GOOGLE_API_KEY', 'GEMINI_API_KEY'],
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['gemini', 'google-gemini'],
    doc: 'https://ai.google.dev/docs',
    source: 'models-dev',
  },
  {
    id: 'google-gemini-cli',
    name: 'Google Gemini (OAuth)',
    transport: 'openai_chat',
    apiKeyEnvVars: [],
    baseUrl: 'cloudcode-pa://google',
    authType: 'oauth_external',
    isAggregator: false,
    aliases: ['gemini-cli', 'gemini-oauth'],
    source: 'hermes',
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    transport: 'openai_chat',
    apiKeyEnvVars: [],
    authType: 'aws_sdk',
    isAggregator: false,
    aliases: ['aws', 'aws-bedrock', 'amazon-bedrock', 'amazon'],
    doc: 'https://docs.aws.amazon.com/bedrock/',
    source: 'hermes',
  },

  // === 聚合器 ===
  {
    id: 'openrouter',
    name: 'OpenRouter',
    transport: 'openai_chat',
    apiKeyEnvVars: ['OPENROUTER_API_KEY', 'OPENAI_API_KEY'],
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'api_key',
    isAggregator: true,
    aliases: [],
    doc: 'https://openrouter.ai/docs',
    source: 'hermes',
  },
  {
    id: 'huggingface',
    name: 'HuggingFace Inference',
    transport: 'openai_chat',
    apiKeyEnvVars: ['HF_TOKEN', 'HUGGING_FACE_TOKEN'],
    baseUrlEnvVar: 'HF_BASE_URL',
    authType: 'api_key',
    isAggregator: true,
    aliases: ['hf', 'hugging-face', 'huggingface-hub'],
    doc: 'https://huggingface.co/docs/api-inference',
    source: 'hermes',
  },
  {
    id: 'vercel',
    name: 'Vercel AI Gateway',
    transport: 'openai_chat',
    apiKeyEnvVars: ['VERCEL_AI_API_KEY'],
    authType: 'api_key',
    isAggregator: true,
    aliases: ['ai-gateway', 'aigateway', 'vercel-ai-gateway'],
    source: 'hermes',
  },
  {
    id: 'opencode',
    name: 'OpenCode Zen',
    transport: 'openai_chat',
    apiKeyEnvVars: ['OPENCODE_ZEN_API_KEY'],
    baseUrlEnvVar: 'OPENCODE_ZEN_BASE_URL',
    authType: 'api_key',
    isAggregator: true,
    aliases: ['opencode-zen', 'zen'],
    source: 'hermes',
  },
  {
    id: 'opencode-go',
    name: 'OpenCode Go',
    transport: 'openai_chat',
    apiKeyEnvVars: ['OPENCODE_GO_API_KEY'],
    baseUrlEnvVar: 'OPENCODE_GO_BASE_URL',
    authType: 'api_key',
    isAggregator: true,
    aliases: ['go', 'opencode-go-sub'],
    source: 'hermes',
  },
  {
    id: 'kilo',
    name: 'Kilo Gateway',
    transport: 'openai_chat',
    apiKeyEnvVars: ['KILO_API_KEY'],
    baseUrlEnvVar: 'KILOCODE_BASE_URL',
    authType: 'api_key',
    isAggregator: true,
    aliases: ['kilocode', 'kilo-code', 'kilo-gateway'],
    source: 'hermes',
  },

  // === 国产大模型 ===
  {
    id: 'deepseek',
    name: 'DeepSeek',
    transport: 'openai_chat',
    apiKeyEnvVars: ['DEEPSEEK_API_KEY'],
    baseUrl: 'https://api.deepseek.com',
    baseUrlEnvVar: 'DEEPSEEK_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['deep-seek'],
    doc: 'https://platform.deepseek.com/api-docs',
    source: 'hermes',
  },
  {
    id: 'alibaba',
    name: '阿里云 (通义/百炼)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['DASHSCOPE_API_KEY'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    baseUrlEnvVar: 'DASHSCOPE_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['dashscope', 'aliyun', 'qwen', 'alibaba-cloud'],
    doc: 'https://help.aliyun.com/zh/dashscope/',
    source: 'hermes',
  },
  {
    id: 'alibaba-coding-plan',
    name: '阿里云 Coding Plan',
    transport: 'openai_chat',
    apiKeyEnvVars: ['ALIBABA_CODING_PLAN_API_KEY'],
    baseUrlEnvVar: 'ALIBABA_CODING_PLAN_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['alibaba_coding', 'alibaba-coding', 'alibaba_coding_plan'],
    source: 'hermes',
  },
  {
    id: 'zai',
    name: '智谱 AI (GLM)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['GLM_API_KEY', 'ZAI_API_KEY', 'Z_AI_API_KEY'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    baseUrlEnvVar: 'GLM_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['glm', 'z-ai', 'z.ai', 'zhipu'],
    doc: 'https://open.bigmodel.cn/dev/api',
    source: 'hermes',
  },
  {
    id: 'kimi-for-coding',
    name: 'Kimi (Moonshot)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['KIMI_API_KEY', 'MOONSHOT_API_KEY'],
    baseUrlEnvVar: 'KIMI_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['kimi', 'kimi-coding', 'kimi-coding-cn', 'moonshot'],
    doc: 'https://platform.moonshot.cn/docs',
    source: 'hermes',
  },
  {
    id: 'stepfun',
    name: '阶跃星辰 (StepFun)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['STEPFUN_API_KEY'],
    baseUrl: 'https://api.stepfun.ai/step_plan/v1',
    baseUrlEnvVar: 'STEPFUN_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['step', 'stepfun-coding-plan'],
    source: 'hermes',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    transport: 'anthropic_messages',
    apiKeyEnvVars: ['MINIMAX_API_KEY'],
    baseUrlEnvVar: 'MINIMAX_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://platform.minimaxi.com/document',
    source: 'hermes',
  },
  {
    id: 'minimax-cn',
    name: 'MiniMax (国内版)',
    transport: 'anthropic_messages',
    apiKeyEnvVars: ['MINIMAX_CN_API_KEY'],
    baseUrlEnvVar: 'MINIMAX_CN_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['minimax-china', 'minimax_cn'],
    source: 'hermes',
  },
  {
    id: 'minimax-oauth',
    name: 'MiniMax (OAuth)',
    transport: 'anthropic_messages',
    apiKeyEnvVars: [],
    baseUrl: 'https://api.minimax.io/anthropic',
    authType: 'oauth_external',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },
  {
    id: 'qwen-oauth',
    name: '通义千问 (OAuth)',
    transport: 'openai_chat',
    apiKeyEnvVars: [],
    baseUrl: 'https://portal.qwen.ai/v1',
    baseUrlEnvVar: 'HERMES_QWEN_BASE_URL',
    authType: 'oauth_external',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },
  {
    id: 'xiaomi',
    name: '小米 (MiMo)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['XIAOMI_API_KEY'],
    baseUrlEnvVar: 'XIAOMI_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['mimo', 'xiaomi-mimo'],
    source: 'hermes',
  },
  {
    id: 'tencent-tokenhub',
    name: '腾讯云 (TokenHub)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['TOKENHUB_API_KEY'],
    baseUrlEnvVar: 'TOKENHUB_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['tencent', 'tokenhub', 'tencent-cloud', 'tencentmaas'],
    source: 'hermes',
  },
  {
    id: 'volcengine',
    name: '火山引擎 (豆包)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['VOLCENGINE_API_KEY', 'ARK_API_KEY'],
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['doubao', 'bytedance', 'ark'],
    source: 'models-dev',
  },
  {
    id: 'baidu',
    name: '百度 (文心一言)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['BAIDU_API_KEY', 'QIANFAN_API_KEY'],
    baseUrl: 'https://qianfan.baidubce.com/v2',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['wenxin', 'qianfan', 'ernie'],
    source: 'models-dev',
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['MOONSHOT_API_KEY'],
    baseUrl: 'https://api.moonshot.cn/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    source: 'models-dev',
  },
  {
    id: 'yi',
    name: '零一万物 (Yi)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['YI_API_KEY'],
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['01-ai', 'lingyiwanwu'],
    source: 'models-dev',
  },
  {
    id: 'baichuan',
    name: '百川智能',
    transport: 'openai_chat',
    apiKeyEnvVars: ['BAICHUAN_API_KEY'],
    baseUrl: 'https://api.baichuan-ai.com/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    source: 'models-dev',
  },
  {
    id: 'siliconflow',
    name: '硅基流动 (SiliconFlow)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['SILICONFLOW_API_KEY'],
    baseUrl: 'https://api.siliconflow.cn/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['silicon'],
    source: 'models-dev',
  },
  {
    id: 'iflytek',
    name: '科大讯飞 (星火)',
    transport: 'openai_chat',
    apiKeyEnvVars: ['IFLYTEK_API_KEY', 'SPARK_API_KEY'],
    authType: 'api_key',
    isAggregator: false,
    aliases: ['spark', 'xinghuo'],
    source: 'models-dev',
  },
  {
    id: 'zhipu',
    name: '智谱 ChatGLM',
    transport: 'openai_chat',
    apiKeyEnvVars: ['ZHIPU_API_KEY'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['chatglm'],
    source: 'models-dev',
  },

  // === AI 编码工具 ===
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    transport: 'openai_chat',
    apiKeyEnvVars: ['COPILOT_GITHUB_TOKEN', 'GH_TOKEN'],
    authType: 'api_key',
    isAggregator: false,
    aliases: ['copilot', 'github'],
    source: 'hermes',
  },
  {
    id: 'copilot-acp',
    name: 'GitHub Copilot ACP',
    transport: 'codex_responses',
    apiKeyEnvVars: [],
    baseUrl: 'acp://copilot',
    baseUrlEnvVar: 'COPILOT_ACP_BASE_URL',
    authType: 'external_process',
    isAggregator: false,
    aliases: ['github-copilot-acp'],
    source: 'hermes',
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    transport: 'codex_responses',
    apiKeyEnvVars: [],
    baseUrl: 'https://chatgpt.com/backend-api/codex',
    authType: 'oauth_external',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },
  {
    id: 'nous',
    name: 'Nous Research',
    transport: 'openai_chat',
    apiKeyEnvVars: ['NOUS_API_KEY'],
    baseUrl: 'https://inference-api.nousresearch.com/v1',
    authType: 'oauth_device_code',
    isAggregator: false,
    aliases: [],
    doc: 'https://nousresearch.com',
    source: 'hermes',
  },

  // === 其他国际供应商 ===
  {
    id: 'xai',
    name: 'xAI (Grok)',
    transport: 'codex_responses',
    apiKeyEnvVars: ['XAI_API_KEY'],
    baseUrl: 'https://api.x.ai/v1',
    baseUrlEnvVar: 'XAI_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['x-ai', 'x.ai', 'grok'],
    doc: 'https://docs.x.ai',
    source: 'hermes',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    transport: 'openai_chat',
    apiKeyEnvVars: ['NVIDIA_API_KEY'],
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    baseUrlEnvVar: 'NVIDIA_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: ['nim', 'nvidia-nim', 'build-nvidia', 'nemotron'],
    doc: 'https://build.nvidia.com',
    source: 'hermes',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['MISTRAL_API_KEY'],
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://docs.mistral.ai',
    source: 'models-dev',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    transport: 'openai_chat',
    apiKeyEnvVars: ['COHERE_API_KEY'],
    baseUrl: 'https://api.cohere.com/v2',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://docs.cohere.com',
    source: 'models-dev',
  },
  {
    id: 'groq',
    name: 'Groq',
    transport: 'openai_chat',
    apiKeyEnvVars: ['GROQ_API_KEY'],
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://console.groq.com/docs',
    source: 'models-dev',
  },
  {
    id: 'together',
    name: 'Together AI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['TOGETHER_API_KEY'],
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://docs.together.ai',
    source: 'models-dev',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['FIREWORKS_API_KEY'],
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://docs.fireworks.ai',
    source: 'models-dev',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    transport: 'openai_chat',
    apiKeyEnvVars: ['PERPLEXITY_API_KEY'],
    baseUrl: 'https://api.perplexity.ai',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://docs.perplexity.ai',
    source: 'models-dev',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    transport: 'openai_chat',
    apiKeyEnvVars: ['REPLICATE_API_TOKEN'],
    baseUrl: 'https://api.replicate.com/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://replicate.com/docs',
    source: 'models-dev',
  },
  {
    id: 'arcee',
    name: 'Arcee AI',
    transport: 'openai_chat',
    apiKeyEnvVars: ['ARCEE_API_KEY'],
    baseUrl: 'https://api.arcee.ai/api/v1',
    baseUrlEnvVar: 'ARCEE_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },
  {
    id: 'gmi',
    name: 'GMI Cloud',
    transport: 'openai_chat',
    apiKeyEnvVars: ['GMI_API_KEY'],
    baseUrl: 'https://api.gmi-serving.com/v1',
    baseUrlEnvVar: 'GMI_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },

  // === 本地/自托管 ===
  {
    id: 'ollama',
    name: 'Ollama (本地)',
    transport: 'openai_chat',
    apiKeyEnvVars: [],
    baseUrl: 'http://localhost:11434/v1',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://ollama.ai',
    source: 'models-dev',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    transport: 'openai_chat',
    apiKeyEnvVars: ['LM_API_KEY'],
    baseUrl: 'http://127.0.0.1:1234/v1',
    baseUrlEnvVar: 'LM_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://lmstudio.ai',
    source: 'hermes',
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama Cloud',
    transport: 'openai_chat',
    apiKeyEnvVars: ['OLLAMA_CLOUD_API_KEY'],
    baseUrlEnvVar: 'OLLAMA_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    source: 'hermes',
  },
  {
    id: 'azure-foundry',
    name: 'Azure AI Foundry',
    transport: 'openai_chat',
    apiKeyEnvVars: ['AZURE_FOUNDRY_API_KEY'],
    baseUrlEnvVar: 'AZURE_FOUNDRY_BASE_URL',
    authType: 'api_key',
    isAggregator: false,
    aliases: [],
    doc: 'https://learn.microsoft.com/azure/ai-foundry',
    source: 'hermes',
  },
]

// ============================================================
// 别名映射表（从 hermes ALIASES 字典提取）
// ============================================================

export const PROVIDER_ALIASES: Record<string, string> = {}

for (const p of PROVIDERS) {
  for (const alias of p.aliases) {
    PROVIDER_ALIASES[alias.toLowerCase()] = p.id
  }
}

// hermes 原始行为：openai 别名指向 openrouter
if (!PROVIDER_ALIASES['openai']) {
  PROVIDER_ALIASES['openai'] = 'openrouter'
}

// ============================================================
// 便捷查找
// ============================================================

export function getProviderById(id: string): ProviderDef | undefined {
  return PROVIDERS.find(p => p.id === id.toLowerCase())
}

export function resolveProvider(nameOrAlias: string): ProviderDef | undefined {
  const normalized = nameOrAlias.toLowerCase().trim()
  const byId = PROVIDERS.find(p => p.id === normalized)
  if (byId) return byId
  const aliasId = PROVIDER_ALIASES[normalized]
  if (aliasId) return getProviderById(aliasId)
  return undefined
}

export function getAllProviderIds(): string[] {
  return PROVIDERS.map(p => p.id)
}

export function getAggregators(): ProviderDef[] {
  return PROVIDERS.filter(p => p.isAggregator)
}

export function getLocalProviders(): ProviderDef[] {
  return PROVIDERS.filter(p => p.baseUrl?.startsWith('http://localhost') || p.baseUrl?.startsWith('http://127.'))
}

export function getOAuthProviders(): ProviderDef[] {
  return PROVIDERS.filter(p => p.authType !== 'api_key')
}
