/**
 * Pre-built provider presets ported from Hermes Agent (29 providers).
 * Each preset maps to an OpenAI-compatible endpoint (or Anthropic/Gemini).
 * Users only need to set the API key to use any provider.
 */

export interface ProviderPreset {
  name: string
  aliases: string[]
  displayName: string
  description: string
  baseUrl: string
  envVar: string
  defaultModel?: string
  fallbackModels: string[]
  signupUrl?: string
  supportsModelFetch?: boolean
  apiType?: 'openai' | 'openai-responses' | 'anthropic' | 'google'
  type: 'openai' | 'anthropic' | 'gemini' | 'skip'
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    name: 'openai',
    aliases: ['chatgpt', 'gpt'],
    displayName: 'OpenAI',
    description: 'OpenAI GPT-5 系列模型',
    baseUrl: 'https://api.openai.com/v1',
    envVar: 'OPENAI_API_KEY',
    defaultModel: 'gpt-5.5',
    fallbackModels: ['gpt-5.5', 'gpt-5.5-instant', 'gpt-5.5-ultra', 'gpt-5.4-image-2', 'gpt-5.1-pro', 'gpt-5.1-mini', 'gpt-5.1-flash', 'gpt-5.1-nano', 'o4-mini', 'gpt-4o'],
    signupUrl: 'https://platform.openai.com/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'deepseek',
    aliases: ['deepseek-chat', 'deepseek-coder'],
    displayName: 'DeepSeek',
    description: 'DeepSeek V4 系列，100M 上下文，MIT 开源',
    baseUrl: 'https://api.deepseek.com/v1',
    envVar: 'DEEPSEEK_API_KEY',
    defaultModel: 'deepseek-v4',
    fallbackModels: ['deepseek-v4', 'deepseek-v4-pro', 'deepseek-v4-flash', 'deepseek-reasoner-v4', 'deepseek-v3.1', 'deepseek-r1', 'deepseek-r1-distill-qwen-32b', 'deepseek-r1-distill-llama-70b'],
    signupUrl: 'https://platform.deepseek.com/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'anthropic',
    aliases: ['claude', 'claude-code'],
    displayName: 'Anthropic',
    description: 'Anthropic Claude 4.5 系列模型',
    baseUrl: 'https://api.anthropic.com',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModel: 'claude-sonnet-4-6',
    fallbackModels: ['claude-sonnet-4-6', 'claude-opus-4-6', 'claude-opus-4-7', 'claude-sonnet-4-20250514', 'claude-haiku-4-20250514', 'claude-3-7-sonnet-latest', 'claude-3-5-haiku-latest'],
    signupUrl: 'https://console.anthropic.com/',
    apiType: 'anthropic',
    type: 'anthropic',
  },
  {
    name: 'gemini',
    aliases: ['google', 'google-ai', 'google-gemini'],
    displayName: 'Google Gemini',
    description: 'Google Gemini 3.x 系列模型',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    envVar: 'GOOGLE_API_KEY',
    defaultModel: 'gemini-3.1-pro',
    fallbackModels: ['gemini-3.1-pro', 'gemini-3.1-ultra', 'gemini-3.1-flash', 'gemini-3.1-flash-lite', 'gemini-3.1-flash-audio', 'gemini-3.1-flash-image', 'gemini-2.5-pro', 'gemini-2.5-flash'],
    signupUrl: 'https://aistudio.google.com/',
    apiType: 'google',
    type: 'gemini',
  },
  {
    name: 'openrouter',
    aliases: ['or'],
    displayName: 'OpenRouter',
    description: 'OpenRouter 200+ 模型聚合平台',
    baseUrl: 'https://openrouter.ai/api/v1',
    envVar: 'OPENROUTER_API_KEY',
    defaultModel: 'deepseek/deepseek-v4',
    fallbackModels: ['deepseek/deepseek-v4', 'deepseek/deepseek-reasoner-v4', 'anthropic/claude-sonnet-4-6', 'openai/gpt-5.5', 'google/gemini-3.1-pro', 'qwen/qwen3.6-plus', 'meta-llama/llama-4-maverick', 'x-ai/grok-4.3'],
    signupUrl: 'https://openrouter.ai/keys',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'alibaba',
    aliases: ['dashscope', 'alibaba-cloud', 'qwen-dashscope'],
    displayName: '阿里云百炼',
    description: '阿里云 DashScope 通义千问系列',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    envVar: 'DASHSCOPE_API_KEY',
    defaultModel: 'qwen3.6-plus',
    fallbackModels: ['qwen3.6-max-preview', 'qwen3.6-plus', 'qwen3.6-flash', 'qwen3.5-omni-plus', 'qwq-plus', 'qwen-coder-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'deepseek-r1', 'glm-5.1', 'minimax-m2.7', 'kimi-k2.6'],
    signupUrl: 'https://dashscope.console.aliyun.com/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'groq',
    aliases: ['groq-cloud'],
    displayName: 'Groq',
    description: 'Groq 超高速推理平台',
    baseUrl: 'https://api.groq.com/openai/v1',
    envVar: 'GROQ_API_KEY',
    defaultModel: 'llama-4-maverick-17b-128e-instruct',
    fallbackModels: ['llama-4-maverick-17b-128e-instruct', 'llama-4-scout-17b-16e-instruct', 'llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mistral-saba-24b', 'qwen-qwq-32b', 'gemma2-9b-it', 'deepseek-r1-distill-llama-70b', 'deepseek-r1-distill-qwen-32b'],
    signupUrl: 'https://console.groq.com/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'mistral',
    aliases: ['mistral-ai'],
    displayName: 'Mistral AI',
    description: 'Mistral AI 欧洲开源模型',
    baseUrl: 'https://api.mistral.ai/v1',
    envVar: 'MISTRAL_API_KEY',
    defaultModel: 'mistral-medium-latest',
    fallbackModels: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest', 'pixtral-large-latest', 'ministral-8b-latest'],
    signupUrl: 'https://console.mistral.ai/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'moonshot',
    aliases: ['kimi', 'moonshot-ai'],
    displayName: 'Moonshot AI',
    description: 'Moonshot AI Kimi K2.5 系列模型',
    baseUrl: 'https://api.moonshot.cn/v1',
    envVar: 'MOONSHOT_API_KEY',
    defaultModel: 'kimi-k2.6',
    fallbackModels: ['kimi-k2.6', 'kimi-k2-instruct', 'kimi-k2-mini', 'moonshot-v1-128k', 'moonshot-v1-32k'],
    signupUrl: 'https://platform.moonshot.cn/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'zai',
    aliases: ['glm', 'zhipu', 'z-ai'],
    displayName: '智谱 AI',
    description: '智谱 Z.AI GLM 系列模型',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    envVar: 'GLM_API_KEY',
    defaultModel: 'glm-5',
    fallbackModels: ['glm-5', 'glm-4-flash', 'glm-4-9b'],
    signupUrl: 'https://open.bigmodel.cn/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'xiaomi',
    aliases: ['mimo', 'xiaomi-mimo'],
    displayName: '小米 MiMo',
    description: '小米 MiMo 模型',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    envVar: 'XIAOMI_API_KEY',
    defaultModel: 'MiMo-MoE-V2-A3B',
    fallbackModels: ['MiMo-MoE-V2-A3B', 'MiMo-V2-7B', 'MiMo-7B-RL'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'xai',
    aliases: ['grok', 'x-ai', 'x.ai'],
    displayName: 'xAI',
    description: 'xAI Grok 4 系列模型',
    baseUrl: 'https://api.x.ai/v1',
    envVar: 'XAI_API_KEY',
    defaultModel: 'grok-4.3',
    fallbackModels: ['grok-4.3', 'grok-3', 'grok-3-mini', 'grok-3-fast', 'grok-2'],
    signupUrl: 'https://console.x.ai/',
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'azure',
    aliases: ['azure-ai', 'azure-ai-foundry'],
    displayName: 'Azure AI',
    description: 'Azure AI Foundry 微软云端模型',
    baseUrl: '',
    envVar: 'AZURE_FOUNDRY_API_KEY',
    fallbackModels: ['gpt-4o', 'gpt-4o-mini', 'phi-4'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'stepfun',
    aliases: ['step'],
    displayName: '阶跃星辰',
    description: '阶跃星辰 StepFun',
    baseUrl: 'https://api.stepfun.ai/step_plan/v1',
    envVar: 'STEPFUN_API_KEY',
    defaultModel: 'step-3.5-flash',
    fallbackModels: ['step-3.5-flash', 'step-3', 'step-2', 'step-2-mini', 'step-1v', 'step-1o-turbo'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'arcee',
    aliases: ['arcee-ai'],
    displayName: 'Arcee AI',
    description: 'Arcee AI 平台',
    baseUrl: 'https://api.arcee.ai/api/v1',
    envVar: 'ARCEEAI_API_KEY',
    fallbackModels: ['arcee-conductor', 'arcee-scribe'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'ai-gateway',
    aliases: ['vercel', 'vercel-ai-gateway'],
    displayName: 'Vercel AI Gateway',
    description: 'Vercel AI Gateway 多模型路由',
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    envVar: 'AI_GATEWAY_API_KEY',
    defaultModel: 'google/gemini-3.1-pro',
    fallbackModels: ['google/gemini-3.1-pro', 'google/gemini-3.1-flash', 'anthropic/claude-sonnet-4-6', 'deepseek/deepseek-v4', 'openai/gpt-5.5', 'meta-llama/llama-4-maverick'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'nous',
    aliases: ['nousresearch'],
    displayName: 'Nous Research',
    description: 'Nous Research 推理平台',
    baseUrl: 'https://inference.nousresearch.com/v1',
    envVar: 'NOUS_API_KEY',
    fallbackModels: ['hermes-3-llama-3.1-405b', 'hermes-3-llama-3.1-70b'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'nvidia',
    aliases: ['nvidia-nim'],
    displayName: 'NVIDIA NIM',
    description: 'NVIDIA NIM 推理平台',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    envVar: 'NVIDIA_API_KEY',
    fallbackModels: ['meta/llama-3.1-405b-instruct', 'meta/llama-3.1-70b-instruct'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'huggingface',
    aliases: ['hf'],
    displayName: 'Hugging Face',
    description: 'Hugging Face Inference API',
    baseUrl: 'https://router.huggingface.co/v1',
    envVar: 'HF_TOKEN',
    fallbackModels: ['meta-llama/Llama-3.1-70B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'ollama-cloud',
    aliases: ['ollama'],
    displayName: 'Ollama',
    description: 'Ollama 本地 / 云端',
    baseUrl: 'https://ollama.com/v1',
    envVar: '',
    defaultModel: 'llama3.1',
    fallbackModels: ['llama3.1', 'mistral', 'qwen2.5'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'kimi-coding',
    aliases: ['kimi-coding-plan'],
    displayName: 'Kimi Coding',
    description: 'Moonshot AI 编程计划端点',
    baseUrl: 'https://api.moonshot.ai/v1',
    envVar: 'MOONSHOT_API_KEY',
    defaultModel: 'kimi-k2.6',
    fallbackModels: ['kimi-k2.5', 'kimi-k2', 'kimi-k2-mini', 'moonshot-v1-128k'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'minimax',
    aliases: [],
    displayName: 'MiniMax',
    description: 'MiniMax 模型平台',
    baseUrl: 'https://api.minimax.io/anthropic',
    envVar: 'MINIMAX_API_KEY',
    fallbackModels: ['minimax-m2.7', 'minimax-m2.7-highspeed', 'minimax-m2.5', 'minimax-m2.5-highspeed'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'kilocode',
    aliases: [],
    displayName: 'Kilocode',
    description: 'Kilocode AI Gateway',
    baseUrl: 'https://api.kilo.ai/api/gateway',
    envVar: 'KILOCODE_API_KEY',
    fallbackModels: [],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'gmi',
    aliases: [],
    displayName: 'GMI Cloud',
    description: 'GMI Cloud 推理平台',
    baseUrl: 'https://api.gmi-serving.com/v1',
    envVar: 'GMI_API_KEY',
    fallbackModels: [],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'qwen',
    aliases: ['qwen-portal', 'qwen-oauth'],
    displayName: '通义千问',
    description: '通义千问 Portal',
    baseUrl: 'https://portal.qwen.ai/v1',
    envVar: 'QWEN_API_KEY',
    defaultModel: 'qwen3.6-plus',
    fallbackModels: ['qwen3.6-max-preview', 'qwen3.6-plus', 'qwen3.6-flash', 'qwen3.5-omni-plus', 'qwq-plus'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'opencode-go',
    aliases: ['opencode_go'],
    displayName: 'OpenCode Go',
    description: 'OpenCode Go 平台',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    envVar: 'OPENCODE_GO_API_KEY',
    defaultModel: 'glm-5',
    fallbackModels: ['glm-5', 'glm-4-plus', 'glm-4-flash', 'glm-4v-plus', 'glm-z1-air'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'doubao',
    aliases: ['bytedance', 'volcengine'],
    displayName: '豆包 (火山引擎)',
    description: '字节跳动豆包系列模型，1M 上下文',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    envVar: 'DOUBAO_API_KEY',
    defaultModel: 'doubao-seed-2-0-pro-260215',
    fallbackModels: ['doubao-seed-2-0-pro-260215', 'doubao-seed-2-0-lite-260115', 'doubao-seed-2-0-mini-260115', 'doubao-seed-1-8-260115', 'doubao-seed-1-6-251015', 'doubao-1-5-pro-256k-250115', 'doubao-1-5-pro-32k-character-250228', 'doubao-1-5-lite-32k-250115', 'doubao-deepseek-r1-250120', 'doubao-deepseek-v3-241226'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'baidu',
    aliases: ['ernie', 'wenxin'],
    displayName: '百度千帆 (文心一言)',
    description: '百度文心大模型系列',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    envVar: 'BAIDU_API_KEY',
    defaultModel: 'ernie-5.0',
    fallbackModels: ['ernie-5.1', 'ernie-4.5-turbo', 'ernie-4.0-turbo-8k', 'ernie-3.5-turbo', 'ernie-speed', 'ernie-lite', 'deepseek-v4-pro', 'deepseek-v4-flash', 'deepseek-r1', 'deepseek-v3.1', 'qwen3-235b', 'kimi-k2-instruct', 'glm-5.1'],
    supportsModelFetch: true,
    apiType: 'openai',
    type: 'openai',
  },
  {
    name: 'baichuan',
    aliases: ['bc'],
    displayName: '百川智能',
    description: '百川大模型系列',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    envVar: 'BAICHUAN_API_KEY',
    defaultModel: 'Baichuan4',
    fallbackModels: ['Baichuan4', 'Baichuan3-Turbo', 'Baichuan2-Turbo', 'Baichuan-Turbo'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'siliconflow',
    aliases: ['silicon', 'sf'],
    displayName: '硅基流动 (SiliconFlow)',
    description: '低价推理平台，支持多种开源模型',
    baseUrl: 'https://api.siliconflow.cn/v1',
    envVar: 'SILICONFLOW_API_KEY',
    defaultModel: 'deepseek-ai/DeepSeek-V4',
    fallbackModels: ['deepseek-ai/DeepSeek-V4', 'deepseek-ai/DeepSeek-V4-Pro', 'deepseek-ai/DeepSeek-V4-Flash', 'deepseek-ai/DeepSeek-V3', 'deepseek-ai/DeepSeek-R1', 'Pro/deepseek-ai/DeepSeek-V4', 'Pro/deepseek-ai/DeepSeek-R1', 'Qwen/Qwen2.5-72B', 'Qwen/Qwen2.5-7B', 'THUDM/GLM-4-9B', 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B', 'BAAI/bge-large-zh-v1.5'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'together',
    aliases: ['togetherai'],
    displayName: 'Together AI',
    description: '开源模型推理平台',
    baseUrl: 'https://api.together.xyz/v1',
    envVar: 'TOGETHER_API_KEY',
    defaultModel: 'meta-llama/Llama-4-Maverick',
    fallbackModels: ['meta-llama/Llama-4-Maverick', 'meta-llama/Llama-4-Scout', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'deepseek-ai/DeepSeek-V4', 'deepseek-ai/DeepSeek-R1', 'Qwen/Qwen3-235B', 'mistralai/Mistral-Small-24B-Instruct', 'google/gemma-4-26b'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'infini',
    aliases: ['infiniai', 'wuwen'],
    displayName: '无问芯穹 (Infini-AI)',
    description: '国产低价推理平台',
    baseUrl: 'https://api.infini-ai.com/maas/v1',
    envVar: 'INFINI_API_KEY',
    defaultModel: 'deepseek-v4',
    fallbackModels: ['deepseek-v4', 'deepseek-v4-pro', 'deepseek-r1', 'qwen3.6-plus', 'glm-5.1', 'kimi-k2.6', 'minimax-m2.7'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'cerebras',
    aliases: ['cerebrasai'],
    displayName: 'Cerebras',
    description: '超高速推理，开源模型',
    baseUrl: 'https://api.cerebras.ai/v1',
    envVar: 'CEREBRAS_API_KEY',
    defaultModel: 'llama-4-maverick-17b-128e',
    fallbackModels: ['llama-4-maverick-17b-128e', 'llama-4-scout-17b-16e', 'llama-3.3-70b', 'llama-3.1-8b', 'qwen-qwq-32b'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'cohere',
    aliases: ['command'],
    displayName: 'Cohere',
    description: 'Cohere Command 系列模型',
    baseUrl: 'https://api.cohere.com/v2',
    envVar: 'COHERE_API_KEY',
    defaultModel: 'command-a',
    fallbackModels: ['command-a', 'command-r-plus', 'command-r'],
    supportsModelFetch: true,
    apiType: 'openai',
    type: 'openai',
  },
  {
    name: 'perplexity',
    aliases: ['pplx'],
    displayName: 'Perplexity',
    description: '联网搜索增强模型',
    baseUrl: 'https://api.perplexity.ai',
    envVar: 'PERPLEXITY_API_KEY',
    defaultModel: 'sonar-pro',
    fallbackModels: ['sonar-pro', 'sonar', 'sonar-reasoning-pro'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'doubao-coding',
    aliases: ['maas'],
    displayName: '豆包 MaaS (Coding)',
    description: '豆包编程专用模型',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    envVar: 'DOUBAO_API_KEY',
    defaultModel: 'doubao-seed-2-0-pro-260215',
    fallbackModels: ['doubao-seed-2-0-pro-260215', 'doubao-1-5-pro-32k-250115'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'yinya',
    aliases: [''],
    displayName: 'Yinya AI',
    description: 'Yinya AI 平台',
    baseUrl: 'https://api.yinya.ai/v1',
    envVar: 'YINYA_AI_API_KEY',
    defaultModel: 'gpt-5.5',
    fallbackModels: ['gpt-5.5', 'claude-sonnet-4-6', 'gemini-3.1-pro'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'hwcloud',
    aliases: ['huawei'],
    displayName: '华为云 ModelArts',
    description: '华为云 AI 推理平台',
    baseUrl: 'https://api.modelarts-maas.com/v1',
    envVar: 'HWCLOUD_API_KEY',
    defaultModel: 'deepseek-v4',
    fallbackModels: ['deepseek-v4', 'deepseek-v4-pro', 'deepseek-r1', 'qwen3.6-plus', 'glm-5.1', 'ernie-4.5-turbo'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'azure-openai',
    aliases: ['ms-openai'],
    displayName: 'Azure OpenAI',
    description: '微软 Azure OpenAI 服务',
    baseUrl: 'https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT',
    envVar: 'AZURE_OPENAI_API_KEY',
    defaultModel: 'gpt-5.5',
    fallbackModels: ['gpt-5.5', 'gpt-5.1-pro', 'gpt-5.4-mini', 'o4-mini'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'xiaoai',
    aliases: ['miai'],
    displayName: '小米 MiMo (云端)',
    description: '小米 MiMo 云端推理服务',
    baseUrl: 'https://api.mimo.xiaomi.com/v1',
    envVar: 'MIMO_CLOUD_API_KEY',
    defaultModel: 'MiMo-MoE-V2-A3B',
    fallbackModels: ['MiMo-MoE-V2-A3B', 'MiMo-V2-7B', 'MiMo-7B-RL'],
    supportsModelFetch: true,
    type: 'openai',
  },
  {
    name: 'custom',
    aliases: ['local', 'self-hosted'],
    displayName: '自定义端点',
    description: '自定义 OpenAI 兼容端点或本地 Ollama',
    baseUrl: 'http://localhost:11434/v1',
    envVar: '',
    defaultModel: 'llama3',
    fallbackModels: ['llama3', 'mistral', 'qwen2'],
    supportsModelFetch: true,
    type: 'openai',
  },
]

export function findPreset(name: string): ProviderPreset | undefined {
  const lower = name.toLowerCase()
  return PROVIDER_PRESETS.find(
    p => p.name === lower || p.aliases.includes(lower)
  )
}

export function getSupportedPresets(): ProviderPreset[] {
  return PROVIDER_PRESETS.filter(p => p.type !== 'skip')
}