/**
 * Pre-built provider presets ported from Hermes Agent (29 providers).
 * Each preset maps to an OpenAI-compatible endpoint (or Anthropic/Gemini).
 * Users only need to set the API key to use any provider.
 */

export interface ProviderPreset {
  name: string
  aliases: string[]
  displayName: string
  description: string
  baseUrl: string
  envVar: string
  defaultModel?: string
  fallbackModels: string[]
  signupUrl?: string
  type: 'openai' | 'anthropic' | 'gemini' | 'skip'
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    name: 'openai',
    aliases: ['chatgpt', 'gpt'],
    displayName: 'OpenAI',
    description: 'OpenAI GPT 系列模型',
    baseUrl: 'https://api.openai.com/v1',
    envVar: 'OPENAI_API_KEY',
    defaultModel: 'gpt-4o',
    fallbackModels: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'],
    signupUrl: 'https://platform.openai.com/',
    type: 'openai',
  },
  {
    name: 'deepseek',
    aliases: ['deepseek-chat', 'deepseek-coder'],
    displayName: 'DeepSeek',
    description: 'DeepSeek 高性价比推理模型',
    baseUrl: 'https://api.deepseek.com/v1',
    envVar: 'DEEPSEEK_API_KEY',
    defaultModel: 'deepseek-chat',
    fallbackModels: ['deepseek-chat', 'deepseek-reasoner'],
    signupUrl: 'https://platform.deepseek.com/',
    type: 'openai',
  },
  {
    name: 'anthropic',
    aliases: ['claude', 'claude-code'],
    displayName: 'Anthropic',
    description: 'Anthropic Claude 系列模型',
    baseUrl: 'https://api.anthropic.com',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModel: 'claude-sonnet-4-20250514',
    fallbackModels: ['claude-sonnet-4-20250514', 'claude-haiku-4-20250514'],
    signupUrl: 'https://console.anthropic.com/',
    type: 'anthropic',
  },
  {
    name: 'gemini',
    aliases: ['google', 'google-ai', 'google-gemini'],
    displayName: 'Google Gemini',
    description: 'Google AI Gemini 系列模型',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    envVar: 'GOOGLE_API_KEY',
    defaultModel: 'gemini-2.5-flash',
    fallbackModels: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.0-flash'],
    signupUrl: 'https://aistudio.google.com/',
    type: 'gemini',
  },
  {
    name: 'openrouter',
    aliases: ['or'],
    displayName: 'OpenRouter',
    description: 'OpenRouter 200+ 模型聚合平台',
    baseUrl: 'https://openrouter.ai/api/v1',
    envVar: 'OPENROUTER_API_KEY',
    defaultModel: 'anthropic/claude-sonnet-4',
    fallbackModels: ['anthropic/claude-sonnet-4', 'openai/gpt-4o', 'deepseek/deepseek-chat', 'google/gemini-2.5-flash', 'qwen/qwen3-plus'],
    signupUrl: 'https://openrouter.ai/keys',
    type: 'openai',
  },
  {
    name: 'alibaba',
    aliases: ['dashscope', 'alibaba-cloud', 'qwen-dashscope'],
    displayName: '阿里云百炼',
    description: '阿里云 DashScope 通义千问系列',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    envVar: 'DASHSCOPE_API_KEY',
    defaultModel: 'qwen-plus',
    fallbackModels: ['qwen-plus', 'qwen-turbo', 'qwen-max'],
    signupUrl: 'https://dashscope.console.aliyun.com/',
    type: 'openai',
  },
  {
    name: 'groq',
    aliases: ['groq-cloud'],
    displayName: 'Groq',
    description: 'Groq 超高速推理平台',
    baseUrl: 'https://api.groq.com/openai/v1',
    envVar: 'GROQ_API_KEY',
    defaultModel: 'llama-3.3-70b-versatile',
    fallbackModels: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    signupUrl: 'https://console.groq.com/',
    type: 'openai',
  },
  {
    name: 'mistral',
    aliases: ['mistral-ai'],
    displayName: 'Mistral AI',
    description: 'Mistral AI 欧洲开源模型',
    baseUrl: 'https://api.mistral.ai/v1',
    envVar: 'MISTRAL_API_KEY',
    defaultModel: 'mistral-large-latest',
    fallbackModels: ['mistral-large-latest', 'mistral-small-latest', 'codestral-latest'],
    signupUrl: 'https://console.mistral.ai/',
    type: 'openai',
  },
  {
    name: 'moonshot',
    aliases: ['kimi', 'moonshot-ai'],
    displayName: 'Moonshot AI',
    description: 'Moonshot AI Kimi 系列模型',
    baseUrl: 'https://api.moonshot.cn/v1',
    envVar: 'MOONSHOT_API_KEY',
    defaultModel: 'moonshot-v1-128k',
    fallbackModels: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
    signupUrl: 'https://platform.moonshot.cn/',
    type: 'openai',
  },
  {
    name: 'zai',
    aliases: ['glm', 'zhipu', 'z-ai'],
    displayName: '智谱 AI',
    description: '智谱 Z.AI GLM 系列模型',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    envVar: 'GLM_API_KEY',
    defaultModel: 'glm-5',
    fallbackModels: ['glm-5', 'glm-4-flash', 'glm-4-9b'],
    signupUrl: 'https://open.bigmodel.cn/',
    type: 'openai',
  },
  {
    name: 'xiaomi',
    aliases: ['mimo', 'xiaomi-mimo'],
    displayName: '小米 MiMo',
    description: '小米 MiMo 模型',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    envVar: 'XIAOMI_API_KEY',
    defaultModel: 'MiMo-MoE-A3B',
    fallbackModels: ['MiMo-MoE-A3B', 'MiMo-7B-RL'],
    type: 'openai',
  },
  {
    name: 'xai',
    aliases: ['grok', 'x-ai', 'x.ai'],
    displayName: 'xAI',
    description: 'xAI Grok 系列模型',
    baseUrl: 'https://api.x.ai/v1',
    envVar: 'XAI_API_KEY',
    defaultModel: 'grok-3',
    fallbackModels: ['grok-3', 'grok-3-mini', 'grok-2'],
    signupUrl: 'https://console.x.ai/',
    type: 'openai',
  },
  {
    name: 'azure',
    aliases: ['azure-ai', 'azure-ai-foundry'],
    displayName: 'Azure AI',
    description: 'Azure AI Foundry 微软云端模型',
    baseUrl: '',
    envVar: 'AZURE_FOUNDRY_API_KEY',
    fallbackModels: ['gpt-4o', 'gpt-4o-mini', 'phi-4'],
    type: 'openai',
  },
  {
    name: 'stepfun',
    aliases: ['step'],
    displayName: '阶跃星辰',
    description: '阶跃星辰 StepFun',
    baseUrl: 'https://api.stepfun.ai/step_plan/v1',
    envVar: 'STEPFUN_API_KEY',
    defaultModel: 'step-3.5-flash',
    fallbackModels: ['step-3.5-flash', 'step-2-16k'],
    type: 'openai',
  },
  {
    name: 'arcee',
    aliases: ['arcee-ai'],
    displayName: 'Arcee AI',
    description: 'Arcee AI 平台',
    baseUrl: 'https://api.arcee.ai/api/v1',
    envVar: 'ARCEEAI_API_KEY',
    fallbackModels: ['arcee-conductor', 'arcee-scribe'],
    type: 'openai',
  },
  {
    name: 'ai-gateway',
    aliases: ['vercel', 'vercel-ai-gateway'],
    displayName: 'Vercel AI Gateway',
    description: 'Vercel AI Gateway 多模型路由',
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    envVar: 'AI_GATEWAY_API_KEY',
    defaultModel: 'google/gemini-3-flash',
    fallbackModels: ['google/gemini-3-flash', 'anthropic/claude-sonnet-4'],
    type: 'openai',
  },
  {
    name: 'nous',
    aliases: ['nousresearch'],
    displayName: 'Nous Research',
    description: 'Nous Research 推理平台',
    baseUrl: 'https://inference.nousresearch.com/v1',
    envVar: 'NOUS_API_KEY',
    fallbackModels: ['hermes-3-llama-3.1-405b', 'hermes-3-llama-3.1-70b'],
    type: 'openai',
  },
  {
    name: 'nvidia',
    aliases: ['nvidia-nim'],
    displayName: 'NVIDIA NIM',
    description: 'NVIDIA NIM 推理平台',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    envVar: 'NVIDIA_API_KEY',
    fallbackModels: ['meta/llama-3.1-405b-instruct', 'meta/llama-3.1-70b-instruct'],
    type: 'openai',
  },
  {
    name: 'huggingface',
    aliases: ['hf'],
    displayName: 'Hugging Face',
    description: 'Hugging Face Inference API',
    baseUrl: 'https://router.huggingface.co/v1',
    envVar: 'HF_TOKEN',
    fallbackModels: ['meta-llama/Llama-3.1-70B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3'],
    type: 'openai',
  },
  {
    name: 'ollama-cloud',
    aliases: ['ollama'],
    displayName: 'Ollama',
    description: 'Ollama 本地 / 云端',
    baseUrl: 'https://ollama.com/v1',
    envVar: '',
    defaultModel: 'llama3.1',
    fallbackModels: ['llama3.1', 'mistral', 'qwen2.5'],
    type: 'openai',
  },
  {
    name: 'kimi-coding',
    aliases: ['kimi-coding-plan'],
    displayName: 'Kimi Coding',
    description: 'Moonshot AI 编程计划端点',
    baseUrl: 'https://api.moonshot.ai/v1',
    envVar: 'MOONSHOT_API_KEY',
    defaultModel: 'kimi-latest',
    fallbackModels: ['kimi-latest', 'moonshot-v1-128k'],
    type: 'openai',
  },
  {
    name: 'minimax',
    aliases: [],
    displayName: 'MiniMax',
    description: 'MiniMax 模型平台',
    baseUrl: 'https://api.minimax.io/anthropic',
    envVar: 'MINIMAX_API_KEY',
    fallbackModels: ['MiniMax-M1', 'MiniMax-Text-01'],
    type: 'openai',
  },
  {
    name: 'kilocode',
    aliases: [],
    displayName: 'Kilocode',
    description: 'Kilocode AI Gateway',
    baseUrl: 'https://api.kilo.ai/api/gateway',
    envVar: 'KILOCODE_API_KEY',
    fallbackModels: [],
    type: 'openai',
  },
  {
    name: 'gmi',
    aliases: [],
    displayName: 'GMI Cloud',
    description: 'GMI Cloud 推理平台',
    baseUrl: 'https://api.gmi-serving.com/v1',
    envVar: 'GMI_API_KEY',
    fallbackModels: [],
    type: 'openai',
  },
  {
    name: 'qwen',
    aliases: ['qwen-portal', 'qwen-oauth'],
    displayName: '通义千问',
    description: '通义千问 Portal',
    baseUrl: 'https://portal.qwen.ai/v1',
    envVar: 'QWEN_API_KEY',
    defaultModel: 'qwen-plus',
    fallbackModels: ['qwen-plus', 'qwen-max', 'qwen-turbo'],
    type: 'openai',
  },
  {
    name: 'opencode-go',
    aliases: ['opencode_go'],
    displayName: 'OpenCode Go',
    description: 'OpenCode Go 平台',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    envVar: 'OPENCODE_GO_API_KEY',
    defaultModel: 'glm-5',
    fallbackModels: ['glm-5', 'glm-4-flash'],
    type: 'openai',
  },
  {
    name: 'custom',
    aliases: ['local', 'self-hosted'],
    displayName: '自定义端点',
    description: '自定义 OpenAI 兼容端点或本地 Ollama',
    baseUrl: 'http://localhost:11434/v1',
    envVar: '',
    defaultModel: 'llama3',
    fallbackModels: ['llama3', 'mistral', 'qwen2'],
    type: 'openai',
  },
]

export function findPreset(name: string): ProviderPreset | undefined {
  const lower = name.toLowerCase()
  return PROVIDER_PRESETS.find(
    p => p.name === lower || p.aliases.includes(lower)
  )
}

export function getSupportedPresets(): ProviderPreset[] {
  return PROVIDER_PRESETS.filter(p => p.type !== 'skip')
}